In [1]:
import numpy as np

In [2]:
distance=[10,14,26,17]
time=[0.5,0.3,0.4,0.2]

In [3]:
np_distance=np.array(distance)
np_time=np.array(time)
print(np_distance)
print(np_time)

[10 14 26 17]
[0.5 0.3 0.4 0.2]


In [5]:
np_speed=np_distance/np_time

print(np_speed)

[20.         46.66666667 65.         85.        ]


In [6]:
np_speed.shape

(4,)

In [7]:
np_speed.ndim

1

In [8]:
np_speed.size

4

In [9]:
np_speed.dtype

dtype('float64')

In [11]:
np_array=np.array([[1,2,3,4],[5,6,7,8]])
print(np_array)

[[1 2 3 4]
 [5 6 7 8]]


In [14]:
np_array.ndim
np_array.size
np_array.dtype
np_array.shape

(2, 4)

In [16]:
for var in np_array:
    for inner_var in var:
        print(inner_var)

1
2
3
4
5
6
7
8


Indexing using Boolean Arrays :

In [18]:
marks=[5,9,10,13,12,15,16,14,17]
np_marks=np.array(marks,dtype=float)
print(np_marks)

[ 5.  9. 10. 13. 12. 15. 16. 14. 17.]


In [19]:
pass_array=np_marks>14
print(pass_array)

[False False False False False  True  True False  True]


In [20]:
np_marks[pass_array]

array([15., 16., 17.])

Concepts of Shallow & Deep Copy :

In [27]:
np_array1=np.array(np.arange(0,10,0.1))
print(np_array1)

np_array2=np_array1
print(np_array2)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3
 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1
 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.  8.1 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9
 9.  9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3
 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1
 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.  8.1 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9
 9.  9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9]


In [29]:
np_array2[0:10]=10
print(np_array2)
print(np_array1)

# This is a shallow copy which means both the objects are same

np_array2 is np_array1

[10.  10.  10.  10.  10.  10.  10.  10.  10.  10.   1.   1.1  1.2  1.3
  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7
  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1
  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5
  5.6  5.7  5.8  5.9  6.   6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
  7.   7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.   8.1  8.2  8.3
  8.4  8.5  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3  9.4  9.5  9.6  9.7
  9.8  9.9]
[10.  10.  10.  10.  10.  10.  10.  10.  10.  10.   1.   1.1  1.2  1.3
  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7
  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1
  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5
  5.6  5.7  5.8  5.9  6.   6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
  7.   7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.   8.1  8.2  8.3
  8.4  8.5  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3  9.4  9.5  9.6

True

In [30]:
np_array1=np.linspace(0,10,100)
print(np_array1)

[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.08080808  8.18181818  8

In [38]:
np_array2=np_array1.view() # creates a shallow copy

In [39]:
print(np_array2)

[23.         23.         23.         23.         23.         23.
 23.         23.         23.         23.          1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.08080808  8.18181818  8.2828282

In [40]:
np_array2[0:10]=23
print(np_array1)
print(np_array2)

[23.         23.         23.         23.         23.         23.
 23.         23.         23.         23.          1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.08080808  8.18181818  8.2828282

In [41]:
np_array1=np.linspace(0,10,100)
print(np_array1)

[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.08080808  8.18181818  8

In [42]:
np_array2=np_array1.copy() # creates a deep copy
print(np_array2)

[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.08080808  8.18181818  8

In [43]:
np_array2[0:10]=23
print(np_array1)
print(np_array2)

[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.08080808  8.18181818  8

Universal Function on Numpy Arrays

In [44]:
np_sqrt=np.array([1,2,3,4,5])
print(np_sqrt)

[1 2 3 4 5]


In [45]:
print(np.sqrt(np_sqrt))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [46]:
print(np.cos(np_sqrt))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [47]:
print(np.sin(np_sqrt))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [49]:
x=(np.sqrt(np_sqrt))
print(np.sqrt(np_sqrt))
np.ceil(x)

[1.         1.41421356 1.73205081 2.         2.23606798]


array([1., 2., 2., 2., 3.])

In [50]:
print(np.exp(np_sqrt))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


Shape Manipulation on Numpy Array

In [57]:
np_example1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np_example1)

np_example1.shape

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


(2, 5)

In [58]:
np_example2=np_example1.ravel() # flattens the array
print(np_example2)
np_example2.shape

[ 1  2  3  4  5  6  7  8  9 10]


(10,)

In [60]:
np_example3=np_example1.reshape(5,2)
print(np_example3)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [69]:
np_example4=np.hsplit(np_example2,2) # splits the array into 2 returns a list
print(np_example4)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]


In [71]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])

print(np.hstack((a,b))) # Stacks the array together


[ 1  2  3  4  5  6  7  8  9 10]


Broadcasting :
NumPy uses broadcasting to carry out arithmetic operations between arrays of different shapes. In this method, NumPy automatically broadcasts the smaller array over the larger array.

In [74]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
c=np.array([1,2,3])

print(a*b)

[ 6 14 24 36 50]


In [75]:
print(a*4)

[ 4  8 12 16 20]


In [76]:
print(a*c)

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

Linear Algebra: Transpose

In [80]:
test_scores=np.array([[1,2,3,4],[5,6,7,8]])
print(test_scores)

[[1 2 3 4]
 [5 6 7 8]]


In [83]:
test_scores.transpose() # transpose of the array

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [84]:
inverse_array=np.array([[10,20],[22,31]])


np.linalg.inv(inverse_array) # inverse of a given array

array([[-0.23846154,  0.15384615],
       [ 0.16923077, -0.07692308]])

In [86]:
np.trace(inverse_array) # sum of the diagonale elements

41