Introduction of Python Numpy

In [2]:
import numpy as np
array1=np.array([1,2,3,4,5,6,7])
print("The array is : ",array1)

The array is :  [1 2 3 4 5 6 7]


In [3]:
array2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
array2.shape

(3, 3)

In [5]:
array1.shape

(7,)

In [6]:
array3=array2.reshape(3,1,3)

In [7]:
array3.shape

(3, 1, 3)

In [8]:
array1.ndim
array2.ndim
array3.ndim

3

In [9]:
array4=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [10]:
array4.shape

(2, 5)

In [11]:
array4.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [12]:
array1.size

7

In [13]:
array2.size

9

In [14]:
array1.dtype

dtype('int32')

In [15]:
array2.dtype

dtype('int32')

In [16]:
array3.dtype

dtype('int32')

In [17]:
array5=np.array([1,2,3,4,5,6],dtype=complex,ndmin=1)

In [18]:
print(array5)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j]


In [19]:
array5[0]=1+45j

In [20]:
print(array5)

[1.+45.j 2. +0.j 3. +0.j 4. +0.j 5. +0.j 6. +0.j]


In [21]:
array5.itemsize

16

Random Arrays from Numpy

In [22]:
array6=np.zeros(shape=[2,3],dtype=complex)
print(array6)

[[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]


In [23]:
array7=np.ones(shape=[4,5],dtype=complex)
print(array7)

[[1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j]]


In [24]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(-5,5,0.1)

array([-5.00000000e+00, -4.90000000e+00, -4.80000000e+00, -4.70000000e+00,
       -4.60000000e+00, -4.50000000e+00, -4.40000000e+00, -4.30000000e+00,
       -4.20000000e+00, -4.10000000e+00, -4.00000000e+00, -3.90000000e+00,
       -3.80000000e+00, -3.70000000e+00, -3.60000000e+00, -3.50000000e+00,
       -3.40000000e+00, -3.30000000e+00, -3.20000000e+00, -3.10000000e+00,
       -3.00000000e+00, -2.90000000e+00, -2.80000000e+00, -2.70000000e+00,
       -2.60000000e+00, -2.50000000e+00, -2.40000000e+00, -2.30000000e+00,
       -2.20000000e+00, -2.10000000e+00, -2.00000000e+00, -1.90000000e+00,
       -1.80000000e+00, -1.70000000e+00, -1.60000000e+00, -1.50000000e+00,
       -1.40000000e+00, -1.30000000e+00, -1.20000000e+00, -1.10000000e+00,
       -1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -1.77635684e-14,  1.00000000e-01,
        2.00000000e-01,  

In [26]:
marks=np.array([[10,20,34],[45,67,89],[67,34,56]])
print(marks)

[[10 20 34]
 [45 67 89]
 [67 34 56]]


In [27]:
#marks in 1st row and 3rd column
marks[0,2]


34

In [28]:
marks[0,2]

34

In [29]:
marks[3:4]

array([], shape=(0, 3), dtype=int32)

In [30]:
marks[1,2]

89

In [31]:
marks[1:2,2]

array([89])

In [32]:
marks1=np.array([[1,2,3],[4,5,6]])
marks2=np.array([[10,11,12],[13,14,15]])

In [33]:
marks1+marks2

array([[11, 13, 15],
       [17, 19, 21]])

In [34]:
marks2-marks1

array([[9, 9, 9],
       [9, 9, 9]])

In [35]:
marks2*marks1

array([[10, 22, 36],
       [52, 70, 90]])

In [36]:
marks1/marks2

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

In [37]:
marks.transpose()

array([[10, 45, 67],
       [20, 67, 34],
       [34, 89, 56]])

In [38]:
marks.sort(axis=0)
print(marks)

[[10 20 34]
 [45 34 56]
 [67 67 89]]


In [39]:
marks.sort(axis=1)
print(marks)

[[10 20 34]
 [34 45 56]
 [67 67 89]]


In [40]:
array8 = np.array([1,0,2,-3,6,8,4,7])


In [41]:
array8

array([ 1,  0,  2, -3,  6,  8,  4,  7])

In [42]:
array4 = np.array([[10,-7,0, 20],
 [-5,1,200,40],[30,1,-1,4]])
print(array4)


[[ 10  -7   0  20]
 [ -5   1 200  40]
 [ 30   1  -1   4]]


In [43]:
array4.sort()
array4

array([[ -7,   0,  10,  20],
       [ -5,   1,  40, 200],
       [ -1,   1,   4,  30]])

In [44]:
array5 = np.array([[10,-7,0, 20],
 [-5,1,200,40],[30,1,-1,4]])
array5.sort(axis=0)
print(array4)

[[ -7   0  10  20]
 [ -5   1  40 200]
 [ -1   1   4  30]]


In [45]:
array1 = np.array([[10, 20], [-30,40]])
array2 = np.zeros((2, 3), dtype=array1.dtype)

array1
array2

array1.shape
array2.shape

np.concatenate((array1,array2), axis=1)

array([[ 10,  20,   0,   0,   0],
       [-30,  40,   0,   0,   0]])

In [46]:
array4=np.ones([4,4])
print(array4)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [47]:
arr1,arr2,arr3=np.split(array4,[1,3])

In [48]:
arr1

array([[1., 1., 1., 1.]])

In [49]:
arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [50]:
arr3

array([[1., 1., 1., 1.]])

In [70]:
array5=np.logspace(start=1,stop=10,num=10)
print(array5)

[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09 1.e+10]


In [71]:
array5=np.linspace(start=1,stop=10,num=10)
print(array5)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


Statistical Operation on Numpy Array

In [51]:
arrayA = np.array([1,0,2,-3,6,8,4,7])
arrayB = np.array([[3,6],[4,2]])


In [52]:
# max element form the whole 1-D array
print(arrayA.max())
print(arrayB.max())

# if axis=1, it gives column wise maximum
print(arrayB.max(axis=1))
print(arrayB.max(axis=0))

8
6
[6 4]
[4 6]


In [53]:
print(arrayA.min())
print(arrayB.min())

-3
2


In [54]:
print(arrayA.mean())
print(arrayB.mean())

3.125
3.75


In [55]:
# Standard Deviation
print(arrayA.std())
print(arrayB.std())

3.550968177835448
1.479019945774904


Loading Arrays from Files


• The parameter skiprows=1 indicates that the
first row is the header row and therefore we
need to skip it as we do not want to load it in
the array.

• The delimiter specifies whether the values are
separated by comma, semicolon, tab or space
(the four are together called whitespace), or any
other character. The default value for delimiter
is space.

• We can also specify the data type of the array
to be created by specifying through the dtype
argument. By default, dtype is float. 

In [60]:

studentdata = np.loadtxt('Data.txt', skiprows=1, delimiter=',',
 dtype = int)

In [57]:
print(studentdata)

[[ 1 36 18 57]
 [ 2 22 23 45]
 [ 3 43 51 37]
 [ 4 41 40 60]
 [ 5 31 45 67]]
